{"news": {"name": "新闻",
          "description": "新闻",
          "data": [{"desc": "keyword",
                    "name": "类型",
                    "data": "新闻"},
                   {"desc": "keyword",
                    "name": "标题",
                    "data": "新闻标题填于此"},
                   {"desc": "plaintext",
                    "name": "摘要",
                    "data": "新闻摘要填于此（可选）"},
                   {"desc": "plaintext",
                    "name": "正文",
                    "data": "新闻正文填于此"}]},
 "inform": {"name": "通知",
            "description": "",
            "data": [{"desc": "keyword",
                      "name": "类型",
                      "data": "通知"},
                     {"desc": "keyword",
                      "name": "标题",
                      "data": "通知标题填于此"}]},
 "activity": {"name": "活动",
              "description": "",
              "data": [{"desc": "keyword",
                        "name": "类型",
                        "data": "活动"},
                       {"desc": "keyword",
                        "name": "标题",
                        "data": "活动标题填于此"},
                       {"desc": "keyword",
                        "name": "主办方",
                        "data": "主办方代码"}]},
 "announce": {"name": "公告",
              "description": "",
              "data": [{"desc": "keyword",
                        "name": "类型",
                        "data": "公告"},
                       {"desc": "keyword",
                        "name": "标题",
                        "data": "公告标题填于此"}]}}
