{"news": {"name": "新闻",
          "description": "新闻",
          "data": [{"desc": "keyword",
                    "name": "类型",
                    "data": "新闻"},
                   {"desc": "keyword",
                    "name": "标题",
                    "data": "新闻标题填于此"},
                   {"desc": "plaintext",
                    "name": "摘要",
                    "data": "新闻摘要填于此（可选）"},
                   {"desc": "plaintext",
                    "name": "正文",
                    "data": "新闻正文填于此"}]},
 "inform": {"name": "通知",
            "description": "",
            "data": [{"desc": "keyword",
                      "name": "类型",
                      "data": "通知"},
                     {"desc": "keyword",
                      "name": "标题",
                      "data": "通知标题填于此"},
                     {"desc": "keyword",
                      "name": "通知到（组织）",
                      "data": "被通知组织代码（可选）"},
                     {"desc": "keyword",
                      "name": "通知到（分组）",
                      "data": "被通知分组（可选；须先填写“通知到（组织）”）"},
                     {"desc": "keyword",
                      "name": "通知到（帐户）",
                      "data": "被通知帐（可选）"},
                     {"desc": "plaintext",
                      "name": "正文",
                      "data": "通知正文填于此"}]},
 "activity": {"name": "活动",
              "description": "",
              "data": [{"desc": "keyword",
                        "name": "类型",
                        "data": "活动"},
                       {"desc": "keyword",
                        "name": "标题",
                        "data": "活动标题填于此"},
                       {"desc": "keyword",
                        "name": "主办方",
                        "data": "主办方代码"},
                       {"desc": "date",
                        "name": "开始时间",
                        "data": {"date": "1970-1-1"}},
                       {"desc": "date",
                        "name": "结束时间",
                        "data": {"date": "1970-1-1"}},
                       {"desc": "plaintext",
                        "name": "正文",
                        "data": "活动介绍填于此"}]},
 "announce": {"name": "告示",
              "description": "",
              "data": [{"desc": "keyword",
                        "name": "类型",
                        "data": "告示"},
                       {"desc": "keyword",
                        "name": "标题",
                        "data": "告示标题填于此"},
                       {"desc": "plaintext",
                        "name": "正文",
                        "data": "告示正文于此"}]}}
